const files = {
  img: [
    require('../assets/images/dammy/1.png'),
    require('../assets/images/dammy/2.png'),
    require('../assets/images/dammy/3.png'),
    require('../assets/images/dammy/4.png'),
    require('../assets/images/dammy/5.png'),
    require('../assets/images/dammy/6.png'),
    require('../assets/images/dammy/8.jpg'),
    require('../assets/images/dammy/9.jpg'),
    require('../assets/images/dammy/10.jpg'),
    require('../assets/images/dammy/11.jpg'),
    require('../assets/images/dammy/12.jpg'),
    require('../assets/images/dammy/13.jpg'),
    require('../assets/images/dammy/14.jpg'),
    require('../assets/images/dammy/15.jpg'),
    require('../assets/images/dammy/16.jpg'),
    require('../assets/images/dammy/17.jpg'),
    require('../assets/images/dammy/18.jpg'),
    require('../assets/images/dammy/19.jpg'),
    require('../assets/images/dammy/20.jpg'),
    require('../assets/images/dammy/21.jpg'),
    require('../assets/images/dammy/22.jpg'),
    require('../assets/images/dammy/23.jpg'),
    require('../assets/images/dammy/24.jpg'),
    require('../assets/images/dammy/25.jpg'),
    require('../assets/images/dammy/26.jpg'),
    require('../assets/images/dammy/27.jpg'),
    require('../assets/images/dammy/28.jpg'),
    require('../assets/images/dammy/29.jpg'),
    require('../assets/images/dammy/30.jpg'),
    require('../assets/images/dammy/31.jpg'),
  ]
}

export default files;
